Repository AI-mazing/finger-swearing-by-country, pull requests merged in 2024-08, with the labels that each got.

#4 draw gesture guideline
  __pycache__/main.cpython-310.pyc
  main.py
  static/head_shoulder_guideline.png
  static/mini.png
  static/ok.png
  static/palm.png
  static/rocknroll.png
  static/rv.png
  static/thumb.png
  static/v.png
Labels: enhancement

#6 파일이름 & dict value 통일
  __pycache__/main.cpython-310.pyc
  main.py
Labels: 버그이슈, 버그해결이슈

#11 db connect
  __pycache__/main.cpython-310.pyc
  main.py
Labels: 버그이슈, 버그해결이슈

#13 gomain button
  app/static/style/style.css
  app/templates/gestureText.html
  main.py
Labels: 기능설계, 김인수

#15 Update README.md
  README.md
Labels: 기능구현이슈, 손석현

#19 [리팩토링] img/nation/Itaila 디렉토리 삭제, __pycache__ 삭제
  __pycache__/main.cpython-310.pyc
  app/static/img/nation/Italia/background.jpg
  app/static/img/nation/Italia/person_angry.jpg
  app/static/img/nation/Italia/person_smile.jpg
Labels: 김인수, 리팩토링
